### PR TITLE
Add browser support

### PR DESCRIPTION
**Pull request by nenadalm**

### CODE REVIEW

**Comment by yogthos** [comment]
Thanks, I wonder if it might be worth looking at [code splitting](https://clojurescript.org/guides/code-splitting) support in the new ClojureScript compiler as well. That might allow running a single Figwheel instance to generate both the server and the client code, as well as making it easy to share code between the two.

**Comment by nenadalm** [comment]
So there would be single `:source-path`
```
src/app/
```
with directories `browser/` and `server/` instead of 2 source paths
```
src/browser/app
src/server/app
```

so man namespace woud be: `(ns app.server.app)` (for server) and `(ns app.browser.app)` for client?

**Comment by yogthos** [comment]
Right, and then the code would be split based on whether it's included in the server app or the browser app.

**Comment by nenadalm** [comment]
@yogthos I wanted to look into modules now, but you need to have same optimization level for all entries.

Since we're using some npm dependencies on server side, it would make it harder. So for now it's not good option for me.

**Comment by yogthos** [comment]
Ah yeah that makes sense. I found using advanced optimizations introduced problems on Node as well.

**Pull request merged**
